version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
      image: redis
      container_name: redis
      restart: always
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data  
        - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      environment:
        TZ: Asia/Shanghai
        LANG: en_US.UTF-8
        
volumes:
  pg-data:
  redis-data: